### ISSUE TITLE
PluginTestCase::BufferedStateStreams load test will fail if the plugin requests a read value smaller than BUFFERED_LOAD_MAX_BYTES

### ISSUE THREAD

**Issue by Stephenmccaul** [robbert-vdh/clap-validator#2]
Looks like its always reading BUFFERED_LOAD_MAX_BYTES rather than taking the minimum with the requested size. with_buffering() looks like its creating a local variable with the same name as the argument. Not sure how scope works in rust but this seems pretty iffy. It would be at least a warning in c++.

If i enforce plugin read calls to be > BUFFERED_LOAD_MAX_BYTES this test will pass for me.

**Comment by robbert-vdh** [comment]
I'm not quite sure what you mean? In the buffered state tests the plugin can read or write at most `n` bytes at a time (where `n = BUFFERED_LOAD_MAX_BYTES = 17` for the reading and `n = BUFFERED_SAVE_MAX_BYTES = 23 for the writing`. These limits as well as the amount of remaining bytes (for the read case) are used to cap the requested read/write size:

https://github.com/robbert-vdh/clapval/blob/125432fe04eb210a3f725eb406c6cdf57c07a7b6/src/plugin/ext/state.rs#L147-L151

That sounds like 'taking the minimum with the requested size' you were referring to, right?

And completely unrelated re:shadowing, there is no shadowing at all in the code here. But even if there was, shading is actually idiomatic in Rust. It's often done for variables because Rust's affine types make it impossible to use a binding that has been consumed (unlike C++'s move semantics where moving is more of a convention and leaves the moved from variable in tact), and for bindings when extracting values from containers through pattern matching or other means.

**Comment by robbert-vdh** [comment]
The test does not fail if the plugin reads less than 17 bytes in a read call. Looking at the code I don't see any reason why it would, and I confirmed that it indeed does not with a plugin that just writes and then reads+asserts three specific bytes in the state save and load functions.

**Comment by Stephenmccaul** [comment]
ok i'm not able to replicate this anymore so was probably something on my side.
